# Generated by Django 4.2 on 2024-10-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommandation',
            options={'verbose_name': 'Recommandation', 'verbose_name_plural': 'Recommandations'},
        ),
        migrations.AddField(
            model_name='recommandation',
            name='cout_estime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommandation',
            name='frequence_repetition',
            field=models.CharField(blank=True, choices=[('quotidien', 'Quotidiennement'), ('hebdomadaire', 'Hebdomadairement'), ('mensuel', 'Mensuel'), ('autre', 'Autre')], max_length=20, null=True),
        ),
    ]
