# Generated by Django 4.2 on 2024-10-23 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommandation', '0003_remove_recommandation_cout_estime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
