# Generated by Django 4.2 on 2024-10-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
    ]
