# Generated by Django 4.2 on 2024-10-25 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommandation', '0006_remove_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(default='like', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('recommandation', 'user')},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
