# Generated by Django 4.2 on 2024-10-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0008_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
