# Generated by Django 4.2 on 2024-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0009_feedback_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10),
        ),
    ]
