# Generated by Django 4.2 on 2024-10-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_zone', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('type_sol', models.CharField(max_length=100)),
                ('besoin_eau', models.FloatField()),
            ],
        ),
    ]
