# Generated by Django 4.2 on 2024-10-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones_irrigation', '0007_zoneirrigation_image_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoneirrigation',
            name='besoin_eau',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance', models.DateField()),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('zone_irrigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='zones_irrigation.zoneirrigation')),
            ],
        ),
    ]
