# Generated by Django 4.2.6 on 2024-10-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_capteur', models.CharField(choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor')], max_length=50)),
                ('localisation', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_installation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
