# Generated by Django 4.2.6 on 2024-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='image_capteur',
            field=models.ImageField(blank=True, null=True, upload_to='images_capteurs/'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='nom_capteur',
            field=models.CharField(default='nom_capteur', max_length=100),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='date_installation',
            field=models.DateField(),
        ),
    ]
