# Generated by Django 4.2.6 on 2024-10-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0002_capteur_image_capteur_capteur_nom_capteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='type_capteur',
            field=models.CharField(choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor')], default='humidity', max_length=50),
        ),
    ]
