# Generated by Django 4.2.6 on 2024-10-27 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0005_rename_humidity_mesure_moisture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='localisation',
            field=models.CharField(default='Tunisie', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Seulement des letters et des espaces sont autorisés')]),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='nom_capteur',
            field=models.CharField(default='nom_capteur', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Seulement des letters et des espaces sont autorisés')]),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='moisture',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
