# Generated by Django 4.2 on 2024-10-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_alter_projectsection_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationEau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('quantite_consommee', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('precipitations', models.FloatField()),
                ('type_culture', models.CharField(max_length=100)),
                ('phase_culture', models.CharField(choices=[('Germination', 'Germination'), ('Croissance', 'Croissance'), ('Floraison', 'Floraison'), ('Maturation', 'Maturation')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '8.water consumption Section',
            },
        ),
    ]
