# Generated by Django 4.2 on 2024-10-28 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_consommationeau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_irrigation', models.CharField(choices=[('Goutte à goutte', 'Goutte à goutte'), ('Aspersion', 'Aspersion'), ('Surface', 'Surface'), ('Sous-irrigation', 'Sous-irrigation')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '8.Irrigation Section',
            },
        ),
        migrations.AddField(
            model_name='consommationeau',
            name='irrigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='home.irrigation'),
        ),
    ]
