# Generated by Django 4.2 on 2024-10-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_irrigation_consommationeau_irrigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommationeau',
            name='irrigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='home.irrigation'),
        ),
    ]
